import type { Metadata } from 'next';
import './globals.css';
import { fontPrimary, fontSecondary } from '@/app/_utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontPrimary.variable} ${fontSecondary.variable}`}>
        {children}
      </body>
    </html>
  );
}
