import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

import { fontPrimary, fontSecondary } from '@app/_utils/fonts';
import SessionProvider from '@app/_context/provider-session';
import { QueryProvider } from '@app/_context/provider-query';
import Header from '@app/_components/layouts/Header';
import Footer from '@app/_components/layouts/Footer';
import { options } from '@app/api/auth/[...nextauth]/options';
import { LoadingProvider } from '@app/_context/loading';
import ToastProvider from '@app/_context/toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  generator: 'Next.js',
  manifest: '/manifest.json',
  keywords: ['nextjs', 'nextjs13', 'next13', 'pwa', 'next-pwa'],
  icons: [
    { rel: 'apple-touch-icon', url: 'icons/icon-128x128.png' },
    { rel: 'icon', url: 'icons/icon-128x128.png' },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body
        className={`${fontPrimary.variable} ${fontSecondary.variable} flex flex-col min-h-screen w-full bg-white font-primary`}>
        <SessionProvider session={session}>
          <QueryProvider>
            <ToastProvider>
              <LoadingProvider>
                <Header />
                {children}
                <Footer />
              </LoadingProvider>
            </ToastProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
